angular.module("LeaderMESfe").factory("shiftServiceDefaultData", function () {
  var shiftData = {
    apiCalled: {},
    dataTimePeriod: 4,
    lastShiftID: null,
    compare: false,
    machineID: null,
    data: null,
    Machines: null,
    summaryBar: null,
    dataLoading: true,
    graphData: {},
    stopEvents: null,
    stopEventsRef: null,
    customDayTab: false,
    error: "",
    stopEventsTotal: 0,
    customDay: null,
    stopEventsReasonFilter: [],
    stopEventsGroupFilter: [],
    stopEventsTotalRef: 0,
    DepartmentID: 0,
    passedTime: 0,
    machineData: null,
    targets: null,
    tab: 4,
    lastHour: false,
    machinesDisplay: {},
    marker: {
      machineID: null,
      machineName: null,
      value: null,
    },
    custom: {
      customTab: null,
      startTime: null,
      endTime: null,
    },
    machinesLoadPointer: {
      selectedM: null,
      selectedH: null,
    },
    criticalEvents: null,
    topStopEvents: null,
    topRejects: null,
    compareWith: "none",
    refShiftData: 1,
    machineAPIData: null,
    customShiftsInsights: [],
  };

  var gridDefault = {
    data: [],
    enableFiltering: false,
    showGridFooter: false,
    enableHiding: false,
    enableColumnResizing: false,
    enableRowSelection: false,
    showClearAllFilters: false,
    enableGridMenu: false,
    enableSelectAll: false,
  };

  var machineContainersDefault = [
    {
      template: "machineStatusGraph",
      name: "Machine Status",
      clone: false,
      order: 1,
      options: {
        machine: true,
        displayFilter: false,
        display: true,
        duplicate: true,
        width: 4,
        disableClose: false,
        disablePie: true,
        selectedGraph: "bar",
        disableTable: true,
        rotateBar: false,
        header: "Machine Status",
        disableBar: true,
        editBtn: true,
        settings: {
          enableEdit: false,
          FieldName: "CycleTime",
          params: { 1: "TimeLeftHour", 2: "CavitiesCurrent", 3: "RejectsTotal", 4: "dummy1", 5: "dummy2" },
          PConfigID: 0,
          jobConfigurationProducts: "sadsdaa",
          scale: 1,
          planClicked: false,
        },
        applyAll: true,
        defaultGraph: "pie",
        height: 500,
        maxHeight: 500,
        tableSelected: false,
        printDiv: "shiftContainerGraphPrint",
        rotateH: false,
        legend: false,
        hideSettings: false,
        sizable: true,
        enableVisibility: false,
        showAllForLegend: false,
        compareBtn: false,
        tableButton: false,
        isTableView: false,
      },
      localMachines: [],
      $$hashKey: "object:107",
    },
    {
      template: "goalsGraph",
      name: "Goals",
      clone: false,
      options: {
        machine: true,
        display: true,
        duplicate: false,
        width: 4,
        disablePie: true,
        selectedGraph: "bar",
        disableTable: true,
        disableClose: false,
        rotateBar: false,
        header: "MACHINE_TARGETS",
        disableBar: true,
        editBtn: true,
        settings: { scale: 1, planClicked: false },
        defaultGraph: "pie",
        disableExport: false,
        height: 500,
        maxHeight: 500,
        tableSelected: false,
        printDiv: "shiftContainerGraphPrint",
        rotateH: false,
        legend: false,
        hideSettings: false,
        sizable: true,
        displayFilter: false,
        enableVisibility: false,
        showAllForLegend: false,
        compareBtn: false,
        tableButton: false,
        isTableView: false,
      },
      localMachines: [],
      $$hashKey: "object:108",
    },
    {
      template: "insightMachineDashboardGraph",
      name: "insights dashboard",
      clone: false,
      options: {
        machine: true,
        display: true,
        duplicate: true,
        width: 4,
        disablePie: true,
        selectedGraph: "bar",
        disableTable: true,
        disableClose: false,
        rotateBar: false,
        header: "",
        disableBar: true,
        tableButton: false,
        settings: {
          parameter: 5,
          parameters: [],
          scale: 1,
          planClicked: false,
        },
        defaultGraph: "pie",
        disableExport: false,
        height: 500,
        maxHeight: 500,
        tableSelected: false,
        printDiv: "shiftContainerGraphPrint",
        rotateH: false,
        legend: false,
        hideSettings: false,
        sizable: true,
        displayFilter: false,
        editBtn: false,
        enableVisibility: false,
        showAllForLegend: false,
        compareBtn: false,
        isTableView: false,
      },
      localMachines: [],
      $$hashKey: "object:109",
    },
    {
      template: "insightMachineDashboardGraph",
      name: "insights dashboard",
      clone: true,
      options: {
        machine: true,
        display: true,
        duplicate: true,
        width: 4,
        disablePie: true,
        selectedGraph: "bar",
        disableTable: true,
        disableClose: false,
        rotateBar: false,
        header: "",
        disableBar: true,
        tableButton: false,
        settings: {
          parameter: 2,
          parameters: [],
          scale: 1,
          planClicked: false,
        },
        defaultGraph: "pie",
        disableExport: false,
        height: 500,
        maxHeight: 500,
        tableSelected: false,
        printDiv: "shiftContainerGraphPrint",
        rotateH: false,
        legend: false,
        hideSettings: false,
        sizable: true,
        displayFilter: false,
        editBtn: false,
        enableVisibility: false,
        showAllForLegend: false,
        compareBtn: false,
        isTableView: false,
      },
      localMachines: [],
      $$hashKey: "object:648",
    },
    {
      template: "insightMachineDashboardGraph",
      name: "insights dashboard",
      clone: true,
      options: {
        machine: true,
        display: true,
        duplicate: true,
        width: 4,
        disablePie: true,
        selectedGraph: "bar",
        disableTable: true,
        disableClose: false,
        rotateBar: false,
        header: "",
        disableBar: true,
        tableButton: false,
        settings: {
          parameter: 1,
          parameters: [],
          scale: 1,
          planClicked: false,
        },
        defaultGraph: "pie",
        disableExport: false,
        height: 500,
        maxHeight: 500,
        tableSelected: false,
        printDiv: "shiftContainerGraphPrint",
        rotateH: false,
        legend: false,
        hideSettings: false,
        sizable: true,
        displayFilter: false,
        editBtn: false,
        enableVisibility: false,
        showAllForLegend: false,
        compareBtn: false,
        isTableView: false,
      },
      localMachines: [],
      $$hashKey: "object:630",
    },
    {
      template: "stopEventsGraph",
      name: "stopEvents2",
      clone: false,
      options: {
        machine: true,
        sliderData: {
          minValue: 26278861,
          maxValue: 26279401,
          options: {
            floor: 26278861,
            ceil: 26279401,
            step: 1,
            id: "slider",
            hideLimitLabels: true,
            hidePointerLabels: true,
            pushRange: false,
            minRange: 1,
            noSwitching: true,
            ticks: {
              6356: {
                startShift: 26278861,
                endShift: 26279401,
                shiftTicks: [26278861, 26278890, 26278920, 26278950, 26278980, 26279010, 26279040, 26279070, 26279100, 26279130, 26279160, 26279190, 26279220, 26279250, 26279280, 26279310, 26279340, 26279370, 26279400],
              },
            },
            tickTotal: 1,
            rightToLeft: false,
          },
        },
        display: false,
        duplicate: true,
        width: 6,
        disablePie: true,
        selectedGraph: "bar",
        header: ["Distribution stop events"],
        disableTable: true,
        rotateBar: false,
        tableButton: true,
        disableClose: false,
        compareBtn: true,
        disableBar: true,
        printDiv: "print-wrapper-distribution",
        settings: {
          parameter: 0,
          compareWith: "none",
          compare: false,
          scale: true,
          group: 0,
          minVal: 5,
          division: true,
          midMinVal: 5,
          midMaxVal: 30,
          maxVal: 30,
          minBar: true,
          midBar: true,
          maxBar: true,
          compareLabel: "NIL",
          planClicked: false,
          filterR: { 0: true, 527: true, selectAll: true },
          filterG: { 2: true, 6: true, selectAll: true },
        },
        stopEventsTotalRef: 0,
        stopEventsRef: null,
        stopEventsTotal: 0,
        stopEvents: null,
        defaultGraph: "pie",
        disableExport: false,
        height: 500,
        maxHeight: 500,
        tableSelected: false,
        rotateH: false,
        legend: false,
        hideSettings: false,
        sizable: true,
        displayFilter: false,
        editBtn: false,
        enableVisibility: false,
        showAllForLegend: false,
        isTableView: false,
      },
      localMachines: [],
      $$hashKey: "object:677",
    },
    {
      template: "topStopEventsGraph",
      name: "Top stop events",
      clone: false,
      options: {
        machine: true,
        display: true,
        duplicate: true,
        width: 4,
        disablePie: true,
        selectedGraph: "bar",
        disableTable: true,
        disableClose: false,
        rotateBar: false,
        header: "Top 5 Stop Events",
        disableBar: true,
        tableButton: true,
        settings: {
          top: 5,
          parameter: 0,
          parameters: [
            { index: 0, value: "TOP_STOP_EVENT_REASONS", $$hashKey: "object:303" },
            { index: 1, value: "TOP_STOP_EVENT_GROUPS", $$hashKey: "object:304" },
          ],
          division: false,
          groupByEvent: true,
          scale: 1,
          planClicked: false,
          filterR: { 0: true, 325: true, 344: true, 527: true, selectAll: true },
          filterG: { 2: true, 5: true, 6: true, 12: true, selectAll: true },
        },
        defaultGraph: "pie",
        disableExport: false,
        height: 500,
        maxHeight: 500,
        tableSelected: false,
        printDiv: "shiftContainerGraphPrint",
        rotateH: false,
        legend: false,
        hideSettings: false,
        sizable: true,
        displayFilter: false,
        editBtn: false,
        enableVisibility: false,
        showAllForLegend: false,
        compareBtn: false,
        isTableView: false,
      },
      localMachines: [],
      $$hashKey: "object:111",
    },
    {
      template: "PEGraph",
      name: "PEGraph",
      clone: false,
      order: 1,
      options: {
        machine: true,
        displayFilter: true,
        display: true,
        duplicate: true,
        width: 6,
        disableClose: false,
        disablePie: true,
        selectedGraph: "bar",
        disableTable: true,
        rotateBar: false,
        header: "PE Data",
        disableBar: true,
        showAllForLegend: true,
        DatePart: 0,
        pointsView: true,
        settings: {
          filterData: false,
          parameter: "CycleTimeLast15Min",
          parameters: [
            "DownTimeEfficiency",
            "EfficiencyTotal",
            "DownTimeEfficiencyOEE",
            "PEE",
            "RejectsEfficiency",
            "CavitiesEfficiency",
            "CycleTimeLast15Min",
            "CycleTime",
            "UnitsProducedTheoreticallyPC",
            "TotalCycles",
            "UnitsProducedTheoretically",
            "ProductWeight",
            "RejectsPCJosh",
            "UnitsProducedOK",
            "TimeLeftHour",
            "TimeLeftHr",
            "UnitsProduced",
            "RejectsTotal",
            "RejectsPC",
            "CycleTimeEfficiency",
          ],
          parametersDisplay: {
            CycleTime: "Cycle Time -  seconds for testing a long name",
            ProductWeight: "ProductWeight",
            TimeLeftHr: "Time Left (Min.)",
            UnitsProduced: "Units Produced",
            CycleTimeLast15Min: "Cycle Time (15Min.)",
            RejectsPCJosh: "Rejects % Shift",
            TotalCycles: "Event Duration (Min)",
            UnitsProducedOK: "Stop - General",
            UnitsProducedTheoreticallyPC: "Event Duration (Hr)",
            RejectsTotal: "Worker",
            RejectsPC: "פוליכד - דוח משימות פתוחות לתלונת לקוח",
            DownTimeEfficiency: "Cnl1MainMatFeeder1",
            DownTimeEfficiencyOEE: "Cnl1MainMatFeeder3",
            CycleTimeEfficiency: "פוליכד - דוח פסולים לא מדווחים",
            RejectsEfficiency: "Cnl1MainMatFeeder5",
            CavitiesEfficiency: "Cnl1MainMatFeeder6",
            EfficiencyTotal: "Cnl1MainMatFeeder2",
            TimeLeftHour: "Time Left (Hr.)",
            PEE: "Cnl1MainMatFeeder4",
            UnitsProducedTheoretically: "M.Change",
          },
          scale: 1,
          planClicked: false,
          machinesLegend: { 1: true },
          autoY: false,
        },
        defaultGraph: "pie",
        disableExport: false,
        height: 500,
        maxHeight: 500,
        tableSelected: false,
        printDiv: "shiftContainerGraphPrint",
        rotateH: false,
        legend: false,
        hideSettings: false,
        sizable: true,
        editBtn: false,
        enableVisibility: false,
        compareBtn: false,
        tableButton: false,
        isTableView: false,
      },
      localMachines: [],
      $$hashKey: "object:112",
    },
    {
      template: "topRejectsGraph",
      name: "Top Rejects",
      clone: false,
      options: {
        machine: true,
        display: true,
        duplicate: false,
        width: 6,
        disablePie: true,
        selectedGraph: "bar",
        disableTable: true,
        disableClose: false,
        rotateBar: false,
        header: "Top 5 Rejects",
        disableBar: true,
        tableButton: false,
        settings: { division: false, scale: 1, planClicked: false, top: 5 },
        defaultGraph: "pie",
        disableExport: false,
        height: 500,
        maxHeight: 500,
        tableSelected: false,
        printDiv: "shiftContainerGraphPrint",
        rotateH: false,
        legend: false,
        hideSettings: false,
        sizable: true,
        displayFilter: false,
        editBtn: false,
        enableVisibility: false,
        showAllForLegend: false,
        compareBtn: false,
        isTableView: false,
      },
      localMachines: [],
      $$hashKey: "object:110",
    },
    {
      template: "unitsProducedGraph",
      name: "Units Produced",
      clone: false,
      options: {
        display: false,
        duplicate: true,
        width: 6,
        disablePie: true,
        selectedGraph: "bar",
        disableTable: true,
        disableClose: false,
        rotateBar: false,
        header: "Units Produced",
        tableButton: true,
        compareBtn: true,
        disableBar: true,
        printDiv: "shiftContainerGraphPrint",
        settings: {
          parameter: 0,
          compareWith: "none",
          compare: false,
          compareLabel: "NIL",
          scale: 1,
          planClicked: false,
        },
        defaultGraph: "pie",
        disableExport: false,
        height: 500,
        maxHeight: 500,
        tableSelected: false,
        rotateH: false,
        legend: false,
        hideSettings: false,
        sizable: true,
        displayFilter: false,
        editBtn: false,
        enableVisibility: false,
        showAllForLegend: false,
        isTableView: false,
      },
      localMachines: [],
      $$hashKey: "object:678",
    },
    {
      template: "shiftTreeGraph",
      name: "Job Tree",
      clone: false,
      options: {
        machine: true,
        display: true,
        duplicate: false,
        width: 12,
        disablePie: true,
        selectedGraph: "bar",
        disableTable: true,
        disableClose: false,
        rotateBar: false,
        header: "Job Tree",
        disableBar: true,
        settings: { jobID: 19830, scale: 1, planClicked: false },
        defaultGraph: "pie",
        disableExport: false,
        height: 500,
        maxHeight: 500,
        tableSelected: false,
        printDiv: "shiftContainerGraphPrint",
        rotateH: false,
        legend: false,
        hideSettings: false,
        sizable: true,
        displayFilter: false,
        editBtn: false,
        enableVisibility: false,
        showAllForLegend: false,
        compareBtn: false,
        tableButton: false,
        isTableView: false,
      },
      localMachines: [],
      $$hashKey: "object:113",
    },
  ];

  var containersDefault = [
    {
      template: "timeGraph",
      name: "timeGraph",
      clone: false,
      ID: "1",
      options: {
        duplicate: true,
        display: false,
        width: 12,
        printDiv: "printShiftTime",
        compareBtn: true,
        disableClose: false,
        sizable: false,
        tableButton: true,
        settings: { compareWith: "none", scale: 0.5, compare: false, compareLabel: "NIL", planClicked: false },
        legend: true,
        line: 1,
        defaultGraph: "pie",
        disableBar: false,
        disablePie: false,
        disableExport: false,
        height: 500,
        maxHeight: 500,
        selectedGraph: "pie",
        tableSelected: false,
        header: null,
        disableTable: false,
        rotateBar: false,
        rotateH: false,
        hideSettings: false,
        displayFilter: false,
        editBtn: false,
        enableVisibility: false,
        showAllForLegend: false,
        isTableView: false,
      },
      localMachines: [],
      isFiltered: false,
    },
    {
      template: "machinesPerformance",
      name: "aggregatedMachinesPerformance",
      clone: false,
      ID: "2",
      options: {
        enableBigCircleIcons: true,
        enableSmallCircleIcons: true,
        insight: false,
        display: true,
        width: 12,
        printDiv: "printShiftTime",
        tableButton: false,
        disableClose: false,
        isTableView: false,
        duplicate: true,
        isActivityGaugeView: false,
        activityGaugeButton: false,
        settings: { compareWith: "none", scale: 0.5, compare: false, compareLabel: "NIL", planClicked: false,targetMode:false,percentageChoice:'target' },
        line: 1,
        disableBar: true,
        disablePie: true,
        disableExport: false,
        selectedGraph: "pic",
        header: null,
        height: "unset",
        optionsWheelClass: "machinesPerformanceOptionsWheel",
        style: { height: "unset", "min-height": "500px", "max-height": "500px" },
        defaultGraph: "pie",
        maxHeight: 500,
        tableSelected: false,
        disableTable: false,
        rotateBar: false,
        rotateH: false,
        legend: false,
        hideSettings: false,
        sizable: true,
        displayFilter: false,
        editBtn: false,
        enableVisibility: false,
        showAllForLegend: false,
        compareBtn: false,
      },
      localMachines: [],
      isFiltered: false,
      change: 0,
      dataArr: {
        highchartData: [
          {
            serieses: [
              { name: "Availability PE ", data: [{ color: "#0080ff", y: 100, radius: "95%", innerRadius: "83%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
              { name: "Quality index ", data: [{ color: "#a3c8ff", y: 100 }] },
              { name: "Cycle Time Efficiency ", data: [{ color: "#29acaf", y: 829, radius: "80%", innerRadius: "68%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
              { name: "PE ", data: [{ color: "#9b86b0", y: 829, radius: "110%", innerRadius: "98%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
              { name: "Unit in cycle Efficiency ", data: [{ color: "#8f8f8f", y: 100 }] },
              { name: "% Reported Events (amount)", data: [{ color: "#f5bcb3", y: 0 }] },
              { name: "% Reported Events (duration)", data: [{ color: "#D47E70", y: 0, radius: "80%", innerRadius: "68%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
            ],
            machineId: 1,
          },
          {
            serieses: [
              { name: "Availability PE ", data: [{ color: "#0080ff", y: 30, radius: "95%", innerRadius: "83%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
              { name: "Quality index ", data: [{ color: "#a3c8ff", y: 100 }] },
              { name: "Cycle Time Efficiency ", data: [{ color: "#29acaf", y: 37, radius: "80%", innerRadius: "68%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
              { name: "PE ", data: [{ color: "#9b86b0", y: 11, radius: "110%", innerRadius: "98%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
              { name: "Unit in cycle Efficiency ", data: [{ color: "#8f8f8f", y: 100 }] },
              { name: "% Reported Events (amount)", data: [{ color: "#f5bcb3", y: 0 }] },
              { name: "% Reported Events (duration)", data: [{ color: "#D47E70", y: 0, radius: "80%", innerRadius: "68%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
            ],
            machineId: 2,
          },
          {
            serieses: [
              { name: "Availability PE ", data: [{ color: "#0080ff", y: 18, radius: "95%", innerRadius: "83%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
              { name: "Quality index ", data: [{ color: "#a3c8ff", y: 100 }] },
              { name: "Cycle Time Efficiency ", data: [{ color: "#29acaf", y: 18, radius: "80%", innerRadius: "68%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
              { name: "PE ", data: [{ color: "#9b86b0", y: 3, radius: "110%", innerRadius: "98%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
              { name: "Unit in cycle Efficiency ", data: [{ color: "#8f8f8f", y: 100 }] },
              { name: "% Reported Events (amount)", data: [{ color: "#f5bcb3", y: 0 }] },
              { name: "% Reported Events (duration)", data: [{ color: "#D47E70", y: 0, radius: "80%", innerRadius: "68%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
            ],
            machineId: 3,
          },
          {
            serieses: [
              { name: "Availability PE ", data: [{ color: "#0080ff", y: 94, radius: "95%", innerRadius: "83%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
              { name: "Quality index ", data: [{ color: "#a3c8ff", y: 100 }] },
              { name: "Cycle Time Efficiency ", data: [{ color: "#29acaf", y: 8, radius: "80%", innerRadius: "68%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
              { name: "PE ", data: [{ color: "#9b86b0", y: 7, radius: "110%", innerRadius: "98%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
              { name: "Unit in cycle Efficiency ", data: [{ color: "#8f8f8f", y: 100 }] },
              { name: "% Reported Events (amount)", data: [{ color: "#f5bcb3", y: 0 }] },
              { name: "% Reported Events (duration)", data: [{ color: "#D47E70", y: 0, radius: "80%", innerRadius: "68%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
            ],
            machineId: 4,
          },
          {
            serieses: [
              { name: "Availability PE ", data: [{ color: "#0080ff", y: 100, radius: "95%", innerRadius: "83%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
              { name: "Quality index ", data: [{ color: "#a3c8ff", y: 100 }] },
              { name: "Cycle Time Efficiency ", data: [{ color: "#29acaf", y: 100, radius: "80%", innerRadius: "68%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
              { name: "PE ", data: [{ color: "#9b86b0", y: 100, radius: "110%", innerRadius: "98%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
              { name: "Unit in cycle Efficiency ", data: [{ color: "#8f8f8f", y: 100 }] },
              { name: "% Reported Events (amount)", data: [{ color: "#f5bcb3", y: 0 }] },
              { name: "% Reported Events (duration)", data: [{ color: "#D47E70", y: 0, radius: "80%", innerRadius: "68%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
            ],
            machineId: 5,
          },
          {
            serieses: [
              { name: "Availability PE ", data: [{ color: "#0080ff", y: 0, radius: "95%", innerRadius: "83%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
              { name: "Quality index ", data: [{ color: "#a3c8ff", y: 0 }] },
              { name: "Cycle Time Efficiency ", data: [{ color: "#29acaf", y: 0, radius: "80%", innerRadius: "68%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
              { name: "PE ", data: [{ color: "#9b86b0", y: 0, radius: "110%", innerRadius: "98%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
              { name: "Unit in cycle Efficiency ", data: [{ color: "#8f8f8f", y: 0 }] },
              { name: "% Reported Events (amount)", data: [{ color: "#f5bcb3", y: 0 }] },
              { name: "% Reported Events (duration)", data: [{ color: "#D47E70", y: 0, radius: "80%", innerRadius: "68%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
            ],
            machineId: 6,
          },
          {
            serieses: [
              { name: "Availability PE ", data: [{ color: "#0080ff", y: 0, radius: "95%", innerRadius: "83%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
              { name: "Quality index ", data: [{ color: "#a3c8ff", y: 0 }] },
              { name: "Cycle Time Efficiency ", data: [{ color: "#29acaf", y: 0, radius: "80%", innerRadius: "68%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
              { name: "PE ", data: [{ color: "#9b86b0", y: 0, radius: "110%", innerRadius: "98%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
              { name: "Unit in cycle Efficiency ", data: [{ color: "#8f8f8f", y: 0 }] },
              { name: "% Reported Events (amount)", data: [{ color: "#f5bcb3", y: 0 }] },
              { name: "% Reported Events (duration)", data: [{ color: "#D47E70", y: 0, radius: "80%", innerRadius: "68%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
            ],
            machineId: 7,
          },
          {
            serieses: [
              { name: "Availability PE ", data: [{ color: "#0080ff", y: 100, radius: "95%", innerRadius: "83%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
              { name: "Quality index ", data: [{ color: "#a3c8ff", y: 100 }] },
              { name: "Cycle Time Efficiency ", data: [{ color: "#29acaf", y: 77, radius: "80%", innerRadius: "68%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
              { name: "PE ", data: [{ color: "#9b86b0", y: 77, radius: "110%", innerRadius: "98%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
              { name: "Unit in cycle Efficiency ", data: [{ color: "#8f8f8f", y: 100 }] },
              { name: "% Reported Events (amount)", data: [{ color: "#f5bcb3", y: 0 }] },
              { name: "% Reported Events (duration)", data: [{ color: "#D47E70", y: 0, radius: "80%", innerRadius: "68%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
            ],
            machineId: 8,
          },
          {
            serieses: [
              { name: "Availability PE ", data: [{ color: "#0080ff", y: 100, radius: "95%", innerRadius: "83%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
              { name: "Quality index ", data: [{ color: "#a3c8ff", y: 100 }] },
              { name: "Cycle Time Efficiency ", data: [{ color: "#29acaf", y: 84, radius: "80%", innerRadius: "68%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
              { name: "PE ", data: [{ color: "#9b86b0", y: 84, radius: "110%", innerRadius: "98%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
              { name: "Unit in cycle Efficiency ", data: [{ color: "#8f8f8f", y: 100 }] },
              { name: "% Reported Events (amount)", data: [{ color: "#f5bcb3", y: 0 }] },
              { name: "% Reported Events (duration)", data: [{ color: "#D47E70", y: 0, radius: "80%", innerRadius: "68%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
            ],
            machineId: 10,
          },
          {
            serieses: [
              { name: "Availability PE ", data: [{ color: "#0080ff", y: 0, radius: "95%", innerRadius: "83%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
              { name: "Quality index ", data: [{ color: "#a3c8ff", y: 0 }] },
              { name: "Cycle Time Efficiency ", data: [{ color: "#29acaf", y: 0, radius: "80%", innerRadius: "68%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
              { name: "PE ", data: [{ color: "#9b86b0", y: 0, radius: "110%", innerRadius: "98%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
              { name: "Unit in cycle Efficiency ", data: [{ color: "#8f8f8f", y: 0 }] },
              { name: "% Reported Events (amount)", data: [{ color: "#f5bcb3", y: 0 }] },
              { name: "% Reported Events (duration)", data: [{ color: "#D47E70", y: 0, radius: "80%", innerRadius: "68%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
            ],
            machineId: 13,
          },
          {
            serieses: [
              { name: "Availability PE ", data: [{ color: "#0080ff", y: 100, radius: "95%", innerRadius: "83%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
              { name: "Quality index ", data: [{ color: "#a3c8ff", y: 100 }] },
              { name: "Cycle Time Efficiency ", data: [{ color: "#29acaf", y: 100, radius: "80%", innerRadius: "68%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
              { name: "PE ", data: [{ color: "#9b86b0", y: 100, radius: "110%", innerRadius: "98%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
              { name: "Unit in cycle Efficiency ", data: [{ color: "#8f8f8f", y: 100 }] },
              { name: "% Reported Events (amount)", data: [{ color: "#f5bcb3", y: 0 }] },
              { name: "% Reported Events (duration)", data: [{ color: "#D47E70", y: 0, radius: "80%", innerRadius: "68%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
            ],
            machineId: 38,
          },
          {
            serieses: [
              { name: "Availability PE ", data: [{ color: "#0080ff", y: 0, radius: "95%", innerRadius: "83%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
              { name: "Quality index ", data: [{ color: "#a3c8ff", y: 100 }] },
              { name: "Cycle Time Efficiency ", data: [{ color: "#29acaf", y: 0, radius: "80%", innerRadius: "68%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
              { name: "PE ", data: [{ color: "#9b86b0", y: 0, radius: "110%", innerRadius: "98%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
              { name: "Unit in cycle Efficiency ", data: [{ color: "#8f8f8f", y: 0 }] },
              { name: "% Reported Events (amount)", data: [{ color: "#f5bcb3", y: 100 }] },
              { name: "% Reported Events (duration)", data: [{ color: "#D47E70", y: 100, radius: "80%", innerRadius: "68%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
            ],
            machineId: 39,
          },
          {
            serieses: [
              { name: "Availability PE ", data: [{ color: "#0080ff", y: 99, radius: "95%", innerRadius: "83%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
              { name: "Quality index ", data: [{ color: "#a3c8ff", y: 100 }] },
              { name: "Cycle Time Efficiency ", data: [{ color: "#29acaf", y: 64, radius: "80%", innerRadius: "68%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
              { name: "PE ", data: [{ color: "#9b86b0", y: 63, radius: "110%", innerRadius: "98%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
              { name: "Unit in cycle Efficiency ", data: [{ color: "#8f8f8f", y: 100 }] },
              { name: "% Reported Events (amount)", data: [{ color: "#f5bcb3", y: 0 }] },
              { name: "% Reported Events (duration)", data: [{ color: "#D47E70", y: 0, radius: "80%", innerRadius: "68%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
            ],
            machineId: 41,
          },
          {
            serieses: [
              { name: "Availability PE ", data: [{ color: "#0080ff", y: 0, radius: "95%", innerRadius: "83%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
              { name: "Quality index ", data: [{ color: "#a3c8ff", y: 0 }] },
              { name: "Cycle Time Efficiency ", data: [{ color: "#29acaf", y: 0, radius: "80%", innerRadius: "68%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
              { name: "PE ", data: [{ color: "#9b86b0", y: 0, radius: "110%", innerRadius: "98%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
              { name: "Unit in cycle Efficiency ", data: [{ color: "#8f8f8f", y: 0 }] },
              { name: "% Reported Events (amount)", data: [{ color: "#f5bcb3", y: 0 }] },
              { name: "% Reported Events (duration)", data: [{ color: "#D47E70", y: 0, radius: "80%", innerRadius: "68%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
            ],
            machineId: 47,
          },
          {
            serieses: [
              { name: "Availability PE ", data: [{ color: "#0080ff", y: 0, radius: "95%", innerRadius: "83%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
              { name: "Quality index ", data: [{ color: "#a3c8ff", y: 100 }] },
              { name: "Cycle Time Efficiency ", data: [{ color: "#29acaf", y: 0, radius: "80%", innerRadius: "68%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
              { name: "PE ", data: [{ color: "#9b86b0", y: 0, radius: "110%", innerRadius: "98%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
              { name: "Unit in cycle Efficiency ", data: [{ color: "#8f8f8f", y: 0 }] },
              { name: "% Reported Events (amount)", data: [{ color: "#f5bcb3", y: 100 }] },
              { name: "% Reported Events (duration)", data: [{ color: "#D47E70", y: 100, radius: "80%", innerRadius: "68%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
            ],
            machineId: 48,
          },
          {
            serieses: [
              { name: "Availability PE ", data: [{ color: "#0080ff", y: 0, radius: "95%", innerRadius: "83%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
              { name: "Quality index ", data: [{ color: "#a3c8ff", y: 100 }] },
              { name: "Cycle Time Efficiency ", data: [{ color: "#29acaf", y: 0, radius: "80%", innerRadius: "68%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
              { name: "PE ", data: [{ color: "#9b86b0", y: 0, radius: "110%", innerRadius: "98%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
              { name: "Unit in cycle Efficiency ", data: [{ color: "#8f8f8f", y: 0 }] },
              { name: "% Reported Events (amount)", data: [{ color: "#f5bcb3", y: 50 }] },
              { name: "% Reported Events (duration)", data: [{ color: "#D47E70", y: 92, radius: "80%", innerRadius: "68%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
            ],
            machineId: 49,
          },
          {
            serieses: [
              { name: "Availability PE ", data: [{ color: "#0080ff", y: 12, radius: "95%", innerRadius: "83%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
              { name: "Quality index ", data: [{ color: "#a3c8ff", y: 100 }] },
              { name: "Cycle Time Efficiency ", data: [{ color: "#29acaf", y: 100, radius: "80%", innerRadius: "68%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
              { name: "PE ", data: [{ color: "#9b86b0", y: 12, radius: "110%", innerRadius: "98%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
              { name: "Unit in cycle Efficiency ", data: [{ color: "#8f8f8f", y: 100 }] },
              { name: "% Reported Events (amount)", data: [{ color: "#f5bcb3", y: 0 }] },
              { name: "% Reported Events (duration)", data: [{ color: "#D47E70", y: 0, radius: "80%", innerRadius: "68%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
            ],
            machineId: 50,
          },
          {
            serieses: [
              { name: "Availability PE ", data: [{ color: "#0080ff", y: 12, radius: "95%", innerRadius: "83%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
              { name: "Quality index ", data: [{ color: "#a3c8ff", y: 100 }] },
              { name: "Cycle Time Efficiency ", data: [{ color: "#29acaf", y: 100, radius: "80%", innerRadius: "68%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
              { name: "PE ", data: [{ color: "#9b86b0", y: 12, radius: "110%", innerRadius: "98%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
              { name: "Unit in cycle Efficiency ", data: [{ color: "#8f8f8f", y: 50 }] },
              { name: "% Reported Events (amount)", data: [{ color: "#f5bcb3", y: 0 }] },
              { name: "% Reported Events (duration)", data: [{ color: "#D47E70", y: 0, radius: "80%", innerRadius: "68%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
            ],
            machineId: 51,
          },
          {
            serieses: [
              { name: "Availability PE ", data: [{ color: "#0080ff", y: 100, radius: "95%", innerRadius: "83%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
              { name: "Quality index ", data: [{ color: "#a3c8ff", y: 100 }] },
              { name: "Cycle Time Efficiency ", data: [{ color: "#29acaf", y: 288, radius: "80%", innerRadius: "68%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
              { name: "PE ", data: [{ color: "#9b86b0", y: 144, radius: "110%", innerRadius: "98%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
              { name: "Unit in cycle Efficiency ", data: [{ color: "#8f8f8f", y: 50 }] },
              { name: "% Reported Events (amount)", data: [{ color: "#f5bcb3", y: 0 }] },
              { name: "% Reported Events (duration)", data: [{ color: "#D47E70", y: 0, radius: "80%", innerRadius: "68%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
            ],
            machineId: 52,
          },
          {
            serieses: [
              { name: "Availability PE ", data: [{ color: "#0080ff", y: 0, radius: "95%", innerRadius: "83%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
              { name: "Quality index ", data: [{ color: "#a3c8ff", y: 0 }] },
              { name: "Cycle Time Efficiency ", data: [{ color: "#29acaf", y: 0, radius: "80%", innerRadius: "68%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
              { name: "PE ", data: [{ color: "#9b86b0", y: 0, radius: "110%", innerRadius: "98%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
              { name: "Unit in cycle Efficiency ", data: [{ color: "#8f8f8f", y: 0 }] },
              { name: "% Reported Events (amount)", data: [{ color: "#f5bcb3", y: 0 }] },
              { name: "% Reported Events (duration)", data: [{ color: "#D47E70", y: 0, radius: "80%", innerRadius: "68%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
            ],
            machineId: 61,
          },
          {
            serieses: [
              { name: "Availability PE ", data: [{ color: "#0080ff", y: 0, radius: "95%", innerRadius: "83%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
              { name: "Quality index ", data: [{ color: "#a3c8ff", y: 0 }] },
              { name: "Cycle Time Efficiency ", data: [{ color: "#29acaf", y: 0, radius: "80%", innerRadius: "68%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
              { name: "PE ", data: [{ color: "#9b86b0", y: 0, radius: "110%", innerRadius: "98%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
              { name: "Unit in cycle Efficiency ", data: [{ color: "#8f8f8f", y: 0 }] },
              { name: "% Reported Events (amount)", data: [{ color: "#f5bcb3", y: 0 }] },
              { name: "% Reported Events (duration)", data: [{ color: "#D47E70", y: 0, radius: "80%", innerRadius: "68%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
            ],
            machineId: 62,
          },
          {
            serieses: [
              { name: "Availability PE ", data: [{ color: "#0080ff", y: 0, radius: "95%", innerRadius: "83%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
              { name: "Quality index ", data: [{ color: "#a3c8ff", y: 0 }] },
              { name: "Cycle Time Efficiency ", data: [{ color: "#29acaf", y: 0, radius: "80%", innerRadius: "68%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
              { name: "PE ", data: [{ color: "#9b86b0", y: 0, radius: "110%", innerRadius: "98%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
              { name: "Unit in cycle Efficiency ", data: [{ color: "#8f8f8f", y: 0 }] },
              { name: "% Reported Events (amount)", data: [{ color: "#f5bcb3", y: 0 }] },
              { name: "% Reported Events (duration)", data: [{ color: "#D47E70", y: 0, radius: "80%", innerRadius: "68%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
            ],
            machineId: 64,
          },
          {
            serieses: [
              { name: "Availability PE ", data: [{ color: "#0080ff", y: 0, radius: "95%", innerRadius: "83%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
              { name: "Quality index ", data: [{ color: "#a3c8ff", y: 100 }] },
              { name: "Cycle Time Efficiency ", data: [{ color: "#29acaf", y: 100, radius: "80%", innerRadius: "68%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
              { name: "PE ", data: [{ color: "#9b86b0", y: 0, radius: "110%", innerRadius: "98%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
              { name: "Unit in cycle Efficiency ", data: [{ color: "#8f8f8f", y: 100 }] },
              { name: "% Reported Events (amount)", data: [{ color: "#f5bcb3", y: 0 }] },
              { name: "% Reported Events (duration)", data: [{ color: "#D47E70", y: 0, radius: "80%", innerRadius: "68%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
            ],
            machineId: 66,
          },
          {
            serieses: [
              { name: "Availability PE ", data: [{ color: "#0080ff", y: 0, radius: "95%", innerRadius: "83%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
              { name: "Quality index ", data: [{ color: "#a3c8ff", y: 100 }] },
              { name: "Cycle Time Efficiency ", data: [{ color: "#29acaf", y: 100, radius: "80%", innerRadius: "68%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
              { name: "PE ", data: [{ color: "#9b86b0", y: 0, radius: "110%", innerRadius: "98%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
              { name: "Unit in cycle Efficiency ", data: [{ color: "#8f8f8f", y: 100 }] },
              { name: "% Reported Events (amount)", data: [{ color: "#f5bcb3", y: 100 }] },
              { name: "% Reported Events (duration)", data: [{ color: "#D47E70", y: 100, radius: "80%", innerRadius: "68%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
            ],
            machineId: 68,
          },
          {
            serieses: [
              { name: "Availability PE ", data: [{ color: "#0080ff", y: 0, radius: "95%", innerRadius: "83%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
              { name: "Quality index ", data: [{ color: "#a3c8ff", y: 0 }] },
              { name: "Cycle Time Efficiency ", data: [{ color: "#29acaf", y: 0, radius: "80%", innerRadius: "68%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
              { name: "PE ", data: [{ color: "#9b86b0", y: 0, radius: "110%", innerRadius: "98%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
              { name: "Unit in cycle Efficiency ", data: [{ color: "#8f8f8f", y: 0 }] },
              { name: "% Reported Events (amount)", data: [{ color: "#f5bcb3", y: 0 }] },
              { name: "% Reported Events (duration)", data: [{ color: "#D47E70", y: 0, radius: "80%", innerRadius: "68%" }], events: {}, point: { events: {} }, customEvents: { series: {}, point: {} } },
            ],
            machineId: 78,
          },
        ],
        displaySettings: {
          displayedKpis: 7,
          availableKpis: [
            {
              "name": "% Reported Events (duration)",
              "display": false,
              "key": "PercentageByDurationOfEvents"
            },
            {
              "name": "Availability PE ",
              "display": true,
              "key": "AvailabilityPE"
            },
            {
              "name": "Cycle Time Efficiency ",
              "display": true,
              "key": "CycleTimeEfficiency"
            },
            {
              "name": "PE ",
              "display": false,
              "key": "PE"
            },
            {
              "name": "Quality index ",
              "display": false,
              "key": "QualityIndex"
            },
            {
              "name": "Unit in cycle Efficiency ",
              "display": false,
              "key": "CavitiesEfficiency"
            },
            {
              "name": "% Reported Events (amount)",
              "display": false,
              "key": "PercentageByNumberOfEvents"
            }
          ],
          maxDisplayedKpis: 4,
          minDisplayedKpis: 1,
          colorSettings: { moreThan: { color: "#7dd963", percentage: 85 }, lessThan: { color: "#fd3030", percentage: 70 }, otherwise: { color: "#a5a67d", percentage: 80 } },
        },
      },
    },
    {
      template: "machinesPerformanceTable",
      name: "detailedMachinesPerformance",
      clone: false,
      ID: "16",
      options: {
        enableBigCircleIcons: true,
        enableSmallCircleIcons: true,
        insight: false,
        display: true,
        width: 12,
        printDiv: "printShiftTime",
        tableButton: false,
        disableClose: false,
        isTableView: false,
        duplicate: true,
        isActivityGaugeView: false,
        activityGaugeButton: false,
        settings: { compareWith: "none", scale: 0.5, compare: false, compareLabel: "NIL", planClicked: false,targetMode:false,percentageChoice:'target' },
        line: 2,
        disableBar: true,
        disablePie: true,
        disableExport: false,
        selectedGraph: "table",
        header: null,
        height: "unset",
        optionsWheelClass: "machinesPerformanceOptionsWheel",
        style: { height: "unset", "min-height": "500px", "max-height": "500px" },
        defaultGraph: "pie",
        maxHeight: 500,
        tableSelected: false,
        disableTable: false,
        rotateBar: false,
        rotateH: false,
        legend: false,
        hideSettings: false,
        sizable: true,
        displayFilter: false,
        editBtn: false,
        enableVisibility: false,
        showAllForLegend: false,
        compareBtn: false,
      },
      localMachines: [],
      isFiltered: false,
      change: 0,
      dataArr: {
        highchartData: [
          {
            serieses: [
              { name: "Availability PE ", data: [{ color: "#0080ff", y: 100, radius: "95%", innerRadius: "83%" }] },
              { name: "Quality index ", data: [{ color: "#a3c8ff", y: 100 }] },
              { name: "Cycle Time Efficiency ", data: [{ color: "#29acaf", y: 829, radius: "80%", innerRadius: "68%" }] },
              { name: "PE ", data: [{ color: "#9b86b0", y: 829, radius: "65%", innerRadius: "53%" }] },
              { name: "Unit in cycle Efficiency ", data: [{ color: "#8f8f8f", y: 100 }] },
              { name: "% Reported Events (amount)", data: [{ color: "#f5bcb3", y: 0 }] },
              { name: "% Reported Events (duration)", data: [{ color: "#D47E70", y: 0, radius: "110%", innerRadius: "98%" }] },
            ],
            machineId: 1,
          },
          {
            serieses: [
              { name: "Availability PE ", data: [{ color: "#0080ff", y: 30 }] },
              { name: "Quality index ", data: [{ color: "#a3c8ff", y: 100 }] },
              { name: "Cycle Time Efficiency ", data: [{ color: "#29acaf", y: 37 }] },
              { name: "PE ", data: [{ color: "#9b86b0", y: 11 }] },
              { name: "Unit in cycle Efficiency ", data: [{ color: "#8f8f8f", y: 100 }] },
              { name: "% Reported Events (amount)", data: [{ color: "#f5bcb3", y: 0 }] },
              { name: "% Reported Events (duration)", data: [{ color: "#D47E70", y: 0 }] },
            ],
            machineId: 2,
          },
          {
            serieses: [
              { name: "Availability PE ", data: [{ color: "#0080ff", y: 18 }] },
              { name: "Quality index ", data: [{ color: "#a3c8ff", y: 100 }] },
              { name: "Cycle Time Efficiency ", data: [{ color: "#29acaf", y: 18 }] },
              { name: "PE ", data: [{ color: "#9b86b0", y: 3 }] },
              { name: "Unit in cycle Efficiency ", data: [{ color: "#8f8f8f", y: 100 }] },
              { name: "% Reported Events (amount)", data: [{ color: "#f5bcb3", y: 0 }] },
              { name: "% Reported Events (duration)", data: [{ color: "#D47E70", y: 0 }] },
            ],
            machineId: 3,
          },
          {
            serieses: [
              { name: "Availability PE ", data: [{ color: "#0080ff", y: 94 }] },
              { name: "Quality index ", data: [{ color: "#a3c8ff", y: 100 }] },
              { name: "Cycle Time Efficiency ", data: [{ color: "#29acaf", y: 8 }] },
              { name: "PE ", data: [{ color: "#9b86b0", y: 7 }] },
              { name: "Unit in cycle Efficiency ", data: [{ color: "#8f8f8f", y: 100 }] },
              { name: "% Reported Events (amount)", data: [{ color: "#f5bcb3", y: 0 }] },
              { name: "% Reported Events (duration)", data: [{ color: "#D47E70", y: 0 }] },
            ],
            machineId: 4,
          },
          {
            serieses: [
              { name: "Availability PE ", data: [{ color: "#0080ff", y: 100 }] },
              { name: "Quality index ", data: [{ color: "#a3c8ff", y: 100 }] },
              { name: "Cycle Time Efficiency ", data: [{ color: "#29acaf", y: 100 }] },
              { name: "PE ", data: [{ color: "#9b86b0", y: 100 }] },
              { name: "Unit in cycle Efficiency ", data: [{ color: "#8f8f8f", y: 100 }] },
              { name: "% Reported Events (amount)", data: [{ color: "#f5bcb3", y: 0 }] },
              { name: "% Reported Events (duration)", data: [{ color: "#D47E70", y: 0 }] },
            ],
            machineId: 5,
          },
          {
            serieses: [
              { name: "Availability PE ", data: [{ color: "#0080ff", y: 0 }] },
              { name: "Quality index ", data: [{ color: "#a3c8ff", y: 0 }] },
              { name: "Cycle Time Efficiency ", data: [{ color: "#29acaf", y: 0 }] },
              { name: "PE ", data: [{ color: "#9b86b0", y: 0 }] },
              { name: "Unit in cycle Efficiency ", data: [{ color: "#8f8f8f", y: 0 }] },
              { name: "% Reported Events (amount)", data: [{ color: "#f5bcb3", y: 0 }] },
              { name: "% Reported Events (duration)", data: [{ color: "#D47E70", y: 0 }] },
            ],
            machineId: 6,
          },
          {
            serieses: [
              { name: "Availability PE ", data: [{ color: "#0080ff", y: 0 }] },
              { name: "Quality index ", data: [{ color: "#a3c8ff", y: 0 }] },
              { name: "Cycle Time Efficiency ", data: [{ color: "#29acaf", y: 0 }] },
              { name: "PE ", data: [{ color: "#9b86b0", y: 0 }] },
              { name: "Unit in cycle Efficiency ", data: [{ color: "#8f8f8f", y: 0 }] },
              { name: "% Reported Events (amount)", data: [{ color: "#f5bcb3", y: 0 }] },
              { name: "% Reported Events (duration)", data: [{ color: "#D47E70", y: 0 }] },
            ],
            machineId: 7,
          },
          {
            serieses: [
              { name: "Availability PE ", data: [{ color: "#0080ff", y: 100 }] },
              { name: "Quality index ", data: [{ color: "#a3c8ff", y: 100 }] },
              { name: "Cycle Time Efficiency ", data: [{ color: "#29acaf", y: 77 }] },
              { name: "PE ", data: [{ color: "#9b86b0", y: 77 }] },
              { name: "Unit in cycle Efficiency ", data: [{ color: "#8f8f8f", y: 100 }] },
              { name: "% Reported Events (amount)", data: [{ color: "#f5bcb3", y: 0 }] },
              { name: "% Reported Events (duration)", data: [{ color: "#D47E70", y: 0 }] },
            ],
            machineId: 8,
          },
          {
            serieses: [
              { name: "Availability PE ", data: [{ color: "#0080ff", y: 100 }] },
              { name: "Quality index ", data: [{ color: "#a3c8ff", y: 100 }] },
              { name: "Cycle Time Efficiency ", data: [{ color: "#29acaf", y: 84 }] },
              { name: "PE ", data: [{ color: "#9b86b0", y: 84 }] },
              { name: "Unit in cycle Efficiency ", data: [{ color: "#8f8f8f", y: 100 }] },
              { name: "% Reported Events (amount)", data: [{ color: "#f5bcb3", y: 0 }] },
              { name: "% Reported Events (duration)", data: [{ color: "#D47E70", y: 0 }] },
            ],
            machineId: 10,
          },
          {
            serieses: [
              { name: "Availability PE ", data: [{ color: "#0080ff", y: 0 }] },
              { name: "Quality index ", data: [{ color: "#a3c8ff", y: 0 }] },
              { name: "Cycle Time Efficiency ", data: [{ color: "#29acaf", y: 0 }] },
              { name: "PE ", data: [{ color: "#9b86b0", y: 0 }] },
              { name: "Unit in cycle Efficiency ", data: [{ color: "#8f8f8f", y: 0 }] },
              { name: "% Reported Events (amount)", data: [{ color: "#f5bcb3", y: 0 }] },
              { name: "% Reported Events (duration)", data: [{ color: "#D47E70", y: 0 }] },
            ],
            machineId: 13,
          },
          {
            serieses: [
              { name: "Availability PE ", data: [{ color: "#0080ff", y: 100 }] },
              { name: "Quality index ", data: [{ color: "#a3c8ff", y: 100 }] },
              { name: "Cycle Time Efficiency ", data: [{ color: "#29acaf", y: 100 }] },
              { name: "PE ", data: [{ color: "#9b86b0", y: 100 }] },
              { name: "Unit in cycle Efficiency ", data: [{ color: "#8f8f8f", y: 100 }] },
              { name: "% Reported Events (amount)", data: [{ color: "#f5bcb3", y: 0 }] },
              { name: "% Reported Events (duration)", data: [{ color: "#D47E70", y: 0 }] },
            ],
            machineId: 38,
          },
          {
            serieses: [
              { name: "Availability PE ", data: [{ color: "#0080ff", y: 0 }] },
              { name: "Quality index ", data: [{ color: "#a3c8ff", y: 100 }] },
              { name: "Cycle Time Efficiency ", data: [{ color: "#29acaf", y: 0 }] },
              { name: "PE ", data: [{ color: "#9b86b0", y: 0 }] },
              { name: "Unit in cycle Efficiency ", data: [{ color: "#8f8f8f", y: 0 }] },
              { name: "% Reported Events (amount)", data: [{ color: "#f5bcb3", y: 100 }] },
              { name: "% Reported Events (duration)", data: [{ color: "#D47E70", y: 100 }] },
            ],
            machineId: 39,
          },
          {
            serieses: [
              { name: "Availability PE ", data: [{ color: "#0080ff", y: 99 }] },
              { name: "Quality index ", data: [{ color: "#a3c8ff", y: 100 }] },
              { name: "Cycle Time Efficiency ", data: [{ color: "#29acaf", y: 64 }] },
              { name: "PE ", data: [{ color: "#9b86b0", y: 63 }] },
              { name: "Unit in cycle Efficiency ", data: [{ color: "#8f8f8f", y: 100 }] },
              { name: "% Reported Events (amount)", data: [{ color: "#f5bcb3", y: 0 }] },
              { name: "% Reported Events (duration)", data: [{ color: "#D47E70", y: 0 }] },
            ],
            machineId: 41,
          },
          {
            serieses: [
              { name: "Availability PE ", data: [{ color: "#0080ff", y: 0 }] },
              { name: "Quality index ", data: [{ color: "#a3c8ff", y: 0 }] },
              { name: "Cycle Time Efficiency ", data: [{ color: "#29acaf", y: 0 }] },
              { name: "PE ", data: [{ color: "#9b86b0", y: 0 }] },
              { name: "Unit in cycle Efficiency ", data: [{ color: "#8f8f8f", y: 0 }] },
              { name: "% Reported Events (amount)", data: [{ color: "#f5bcb3", y: 0 }] },
              { name: "% Reported Events (duration)", data: [{ color: "#D47E70", y: 0 }] },
            ],
            machineId: 47,
          },
          {
            serieses: [
              { name: "Availability PE ", data: [{ color: "#0080ff", y: 0 }] },
              { name: "Quality index ", data: [{ color: "#a3c8ff", y: 100 }] },
              { name: "Cycle Time Efficiency ", data: [{ color: "#29acaf", y: 0 }] },
              { name: "PE ", data: [{ color: "#9b86b0", y: 0 }] },
              { name: "Unit in cycle Efficiency ", data: [{ color: "#8f8f8f", y: 0 }] },
              { name: "% Reported Events (amount)", data: [{ color: "#f5bcb3", y: 100 }] },
              { name: "% Reported Events (duration)", data: [{ color: "#D47E70", y: 100 }] },
            ],
            machineId: 48,
          },
          {
            serieses: [
              { name: "Availability PE ", data: [{ color: "#0080ff", y: 0 }] },
              { name: "Quality index ", data: [{ color: "#a3c8ff", y: 100 }] },
              { name: "Cycle Time Efficiency ", data: [{ color: "#29acaf", y: 0 }] },
              { name: "PE ", data: [{ color: "#9b86b0", y: 0 }] },
              { name: "Unit in cycle Efficiency ", data: [{ color: "#8f8f8f", y: 0 }] },
              { name: "% Reported Events (amount)", data: [{ color: "#f5bcb3", y: 50 }] },
              { name: "% Reported Events (duration)", data: [{ color: "#D47E70", y: 92 }] },
            ],
            machineId: 49,
          },
          {
            serieses: [
              { name: "Availability PE ", data: [{ color: "#0080ff", y: 12 }] },
              { name: "Quality index ", data: [{ color: "#a3c8ff", y: 100 }] },
              { name: "Cycle Time Efficiency ", data: [{ color: "#29acaf", y: 100 }] },
              { name: "PE ", data: [{ color: "#9b86b0", y: 12 }] },
              { name: "Unit in cycle Efficiency ", data: [{ color: "#8f8f8f", y: 100 }] },
              { name: "% Reported Events (amount)", data: [{ color: "#f5bcb3", y: 0 }] },
              { name: "% Reported Events (duration)", data: [{ color: "#D47E70", y: 0 }] },
            ],
            machineId: 50,
          },
          {
            serieses: [
              { name: "Availability PE ", data: [{ color: "#0080ff", y: 12 }] },
              { name: "Quality index ", data: [{ color: "#a3c8ff", y: 100 }] },
              { name: "Cycle Time Efficiency ", data: [{ color: "#29acaf", y: 100 }] },
              { name: "PE ", data: [{ color: "#9b86b0", y: 12 }] },
              { name: "Unit in cycle Efficiency ", data: [{ color: "#8f8f8f", y: 50 }] },
              { name: "% Reported Events (amount)", data: [{ color: "#f5bcb3", y: 0 }] },
              { name: "% Reported Events (duration)", data: [{ color: "#D47E70", y: 0 }] },
            ],
            machineId: 51,
          },
          {
            serieses: [
              { name: "Availability PE ", data: [{ color: "#0080ff", y: 100 }] },
              { name: "Quality index ", data: [{ color: "#a3c8ff", y: 100 }] },
              { name: "Cycle Time Efficiency ", data: [{ color: "#29acaf", y: 288 }] },
              { name: "PE ", data: [{ color: "#9b86b0", y: 144 }] },
              { name: "Unit in cycle Efficiency ", data: [{ color: "#8f8f8f", y: 50 }] },
              { name: "% Reported Events (amount)", data: [{ color: "#f5bcb3", y: 0 }] },
              { name: "% Reported Events (duration)", data: [{ color: "#D47E70", y: 0 }] },
            ],
            machineId: 52,
          },
          {
            serieses: [
              { name: "Availability PE ", data: [{ color: "#0080ff", y: 0 }] },
              { name: "Quality index ", data: [{ color: "#a3c8ff", y: 0 }] },
              { name: "Cycle Time Efficiency ", data: [{ color: "#29acaf", y: 0 }] },
              { name: "PE ", data: [{ color: "#9b86b0", y: 0 }] },
              { name: "Unit in cycle Efficiency ", data: [{ color: "#8f8f8f", y: 0 }] },
              { name: "% Reported Events (amount)", data: [{ color: "#f5bcb3", y: 0 }] },
              { name: "% Reported Events (duration)", data: [{ color: "#D47E70", y: 0 }] },
            ],
            machineId: 61,
          },
          {
            serieses: [
              { name: "Availability PE ", data: [{ color: "#0080ff", y: 0 }] },
              { name: "Quality index ", data: [{ color: "#a3c8ff", y: 0 }] },
              { name: "Cycle Time Efficiency ", data: [{ color: "#29acaf", y: 0 }] },
              { name: "PE ", data: [{ color: "#9b86b0", y: 0 }] },
              { name: "Unit in cycle Efficiency ", data: [{ color: "#8f8f8f", y: 0 }] },
              { name: "% Reported Events (amount)", data: [{ color: "#f5bcb3", y: 0 }] },
              { name: "% Reported Events (duration)", data: [{ color: "#D47E70", y: 0 }] },
            ],
            machineId: 62,
          },
          {
            serieses: [
              { name: "Availability PE ", data: [{ color: "#0080ff", y: 0 }] },
              { name: "Quality index ", data: [{ color: "#a3c8ff", y: 0 }] },
              { name: "Cycle Time Efficiency ", data: [{ color: "#29acaf", y: 0 }] },
              { name: "PE ", data: [{ color: "#9b86b0", y: 0 }] },
              { name: "Unit in cycle Efficiency ", data: [{ color: "#8f8f8f", y: 0 }] },
              { name: "% Reported Events (amount)", data: [{ color: "#f5bcb3", y: 0 }] },
              { name: "% Reported Events (duration)", data: [{ color: "#D47E70", y: 0 }] },
            ],
            machineId: 64,
          },
          {
            serieses: [
              { name: "Availability PE ", data: [{ color: "#0080ff", y: 0 }] },
              { name: "Quality index ", data: [{ color: "#a3c8ff", y: 100 }] },
              { name: "Cycle Time Efficiency ", data: [{ color: "#29acaf", y: 100 }] },
              { name: "PE ", data: [{ color: "#9b86b0", y: 0 }] },
              { name: "Unit in cycle Efficiency ", data: [{ color: "#8f8f8f", y: 100 }] },
              { name: "% Reported Events (amount)", data: [{ color: "#f5bcb3", y: 0 }] },
              { name: "% Reported Events (duration)", data: [{ color: "#D47E70", y: 0 }] },
            ],
            machineId: 66,
          },
          {
            serieses: [
              { name: "Availability PE ", data: [{ color: "#0080ff", y: 0 }] },
              { name: "Quality index ", data: [{ color: "#a3c8ff", y: 100 }] },
              { name: "Cycle Time Efficiency ", data: [{ color: "#29acaf", y: 100 }] },
              { name: "PE ", data: [{ color: "#9b86b0", y: 0 }] },
              { name: "Unit in cycle Efficiency ", data: [{ color: "#8f8f8f", y: 100 }] },
              { name: "% Reported Events (amount)", data: [{ color: "#f5bcb3", y: 100 }] },
              { name: "% Reported Events (duration)", data: [{ color: "#D47E70", y: 100 }] },
            ],
            machineId: 68,
          },
          {
            serieses: [
              { name: "Availability PE ", data: [{ color: "#0080ff", y: 0 }] },
              { name: "Quality index ", data: [{ color: "#a3c8ff", y: 0 }] },
              { name: "Cycle Time Efficiency ", data: [{ color: "#29acaf", y: 0 }] },
              { name: "PE ", data: [{ color: "#9b86b0", y: 0 }] },
              { name: "Unit in cycle Efficiency ", data: [{ color: "#8f8f8f", y: 0 }] },
              { name: "% Reported Events (amount)", data: [{ color: "#f5bcb3", y: 0 }] },
              { name: "% Reported Events (duration)", data: [{ color: "#D47E70", y: 0 }] },
            ],
            machineId: 78,
          },
        ],
        displaySettings: {
          displayedKpis: 7,
          availableKpis: [
            {
              "name": "Performance",
              "key": "UnitsRatio",
              "display": true
            },
            {
              "name": "Good Units",
              "key": "UnitsProducedOK",
              "display": true
            },
            {
              "name": "Rejects",
              "key": "RejectsTotal",
              "display": true
            },
            {
              "name": "Theoretical Units",
              "key": "UnitsProducedTheoretically",
              "display": true
            },
            {
              "name": "Total Units Shift",
              "key": "TotalUnitsJosh",
              "display": false
            },
            {
              "name": "Production Time",
              "key": "ProductionTime",
              "display": true
            },
            {
              "name": "Down Time",
              "key": "DownTime",
              "display": true
            },
            {
              "name": "Inactive Time",
              "key": "InActiveTime",
              "display": true
            },
            {
              "name": "Availability PE ",
              "key": "AvailabilityPE",
              "display": true
            },
            {
              "name": "Cycle Time Efficiency ",
              "key": "CycleTimeEfficiency",
              "display": true
            },
            {
              "name": "Quality index ",
              "key": "QualityIndex",
              "display": true
            },
            {
              "name": "PE ",
              "key": "PE",
              "display": true
            },
            {
              "name": "Active Time",
              "key": "ActiveTime",
              "display": false
            },
            {
              "name": "Number Of Setups",
              "key": "NumberOfSetups",
              "display": true
            },
            {
              "name": "Setup duration",
              "key": "SetupDuration",
              "display": true
            },
            {
              "name": "Unit in cycle Efficiency ",
              "key": "CavitiesEfficiency",
              "display": false
            },
            {
              "name": "% Reported Events (amount)",
              "key": "PercentageByNumberOfEvents",
              "display": true
            },
            {
              "name": "Number Of Events",
              "key": "NumberOfEvents",
              "display": false
            },
            {
              "name": "Number Of Reported Events",
              "key": "NumberOfReportedEvents",
              "display": false
            },
            {
              "name": "% Reported Events (duration)",
              "key": "PercentageByDurationOfEvents",
              "display": false
            },
            {
              "name": "Reported Events Duration",
              "key": "ReportedEventsDuration",
              "display": false
            },
            {
              "name": "Event duration",
              "key": "EventsDuration",
              "display": false
            }
          ],
          maxDisplayedKpis: 9007199254740991,
          minDisplayedKpis: 1,
          colorSettings: { moreThan: { color: "#7dd963", percentage: 85 }, lessThan: { color: "#fd3030", percentage: 70 }, otherwise: { color: "#a5a67d", percentage: 80 } },
        },
      },
    },
    {
      template: "PEGraph",
      name: "PEGraph",
      clone: false,
      order: 1,
      ID: "4",
      options: {
        displayFilter: true,
        display: false,
        enableVisibility: true,
        duplicate: true,
        width: 6,
        disableClose: false,
        disablePie: true,
        selectedGraph: "bar",
        disableTable: true,
        rotateBar: false,
        header: "PE Data",
        disableBar: true,
        showAllForLegend: true,
        DatePart: 0,
        pointsView: true,
        settings: {
          filterData: false,
          parameter: "PEE",
          parameters: [
            "DownTimeEfficiencyOEE",
            "DownTimeEfficiency",
            "AverageCycle",
            "CycleTimeLast15Min",
            "CycleTime",
            "CycleTimeEfficiency",
            "UnitsProducedOK",
            "EfficiencyTotal",
            "PEE",
            "UnitsProducedTheoreticallyPC",
            "ProductWeight",
            "RejectsEfficiency",
            "RejectsTotal",
            "RejectsPCJosh",
            "RejectsPC",
            "TimeLeftHour",
            "TimeLeftHr",
            "TotalCycles",
            "UnitWeight",
            "CavitiesEfficiency",
            "UnitsProduced",
            "UnitsProducedTheoretically",
            "KWH",
          ],
          minY: null,
          maxY: null,
          autoY: true,
          showLimits: false,
          filterPoints: false,
          parametersDisplay: {
            TotalCycles: "Total Cycles",
            UnitsProducedOK: "Good Units",
            UnitsProducedTheoretically: "Units Produced Theoretically",
            UnitsProducedTheoreticallyPC: "Performance Compliance PercentageL",
            RejectsTotal: "Rejected Units",
            RejectsPC: "Rejects precentage",
            DownTimeEfficiency: "Availability PE",
            DownTimeEfficiencyOEE: "Availability OEE1",
            ProductWeight: "ProductWeight",
            TimeLeftHr: "Time Left (Min.)",
            TimeLeftHour: "Time Left (Hr.)",
            UnitsProduced: "Units Produced",
            CycleTimeLast15Min: "Cycle Time (15Min.)",
            RejectsPCJosh: "Rejects % Shift",
            RejectsEfficiency: "Quality index",
            CavitiesEfficiency: "Unit in cycle Efficiency",
            EfficiencyTotal: "OEE1",
            CycleTime: "Cycle Time -  seconds for testing a long name",
            PEE: "PE",
            CycleTimeEfficiency: "Cycle Time Efficiency",
            UnitWeight: "Unit Weight",
            AverageCycle: "AverageCycle",
            KWH: "kWh",
          },
          scale: 1,
          planClicked: false,
          machinesLegend: { 1: false, 2: true, 3: false, 4: false, 5: true, 6: false, 7: false, 8: false, 10: false, 13: false, 38: false, 39: false, 41: false, 47: false, 48: false, 49: false, 50: false, 51: false, 52: false, 61: false, 62: false, 64: false, 66: false, 68: false },
        },
        line: 1,
        defaultGraph: "pie",
        disableExport: false,
        height: 500,
        maxHeight: 500,
        tableSelected: false,
        printDiv: "shiftContainerGraphPrint",
        rotateH: false,
        legend: false,
        hideSettings: false,
        sizable: true,
        editBtn: false,
        compareBtn: false,
        tableButton: false,
        isTableView: false,
      },
      localMachines: [],
      isFiltered: false,
    },
    {
      template: "stopEventsGraph",
      name: "stopEvents2",
      clone: false,
      ID: "5",
      options: {
        sliderData: {
          minValue: 26278861,
          maxValue: 26279401,
          options: {
            floor: 26278861,
            ceil: 26279401,
            step: 1,
            id: "slider",
            hideLimitLabels: true,
            hidePointerLabels: true,
            pushRange: false,
            minRange: 1,
            noSwitching: true,
            ticks: { 6356: { startShift: 26278861, endShift: 26279401, shiftTicks: [26278861, 26278890, 26278920, 26278950, 26278980, 26279010, 26279040, 26279070, 26279100, 26279130, 26279160, 26279190, 26279220, 26279250, 26279280, 26279310, 26279340, 26279370, 26279400], xIf: 60, x: 60 } },
            tickTotal: 1,
            rightToLeft: false,
          },
        },
        display: false,
        duplicate: true,
        width: 6,
        disablePie: true,
        selectedGraph: "bar",
        header: ["Distribution stop events", "Group By Machine"],
        disableTable: true,
        rotateBar: false,
        tableButton: true,
        disableClose: false,
        compareBtn: true,
        disableBar: true,
        printDiv: "print-wrapper-distribution",
        settings: {
          compareWith: "none",
          compare: false,
          scale: 1,
          group: 1,
          minVal: 5,
          division: true,
          midMinVal: 5,
          midMaxVal: 30,
          maxVal: 30,
          minBar: true,
          midBar: true,
          maxBar: true,
          compareLabel: "NIL",
          timeV: true,
          planClicked: false,
          filterR: { 0: true, 2: true, 16: true, 18: true, 100: true, 310: true, 527: true, selectAll: true },
          filterG: { 1: true, 2: true, 4: true, 6: true, 10: true, 12: true, selectAll: true },
        },
        stopEventsTotalRef: 0,
        stopEventsRef: null,
        stopEventsTotal: 0,
        stopEvents: null,
        line: 1,
        defaultGraph: "pie",
        disableExport: false,
        height: 500,
        maxHeight: 500,
        tableSelected: false,
        rotateH: false,
        legend: false,
        hideSettings: false,
        sizable: true,
        displayFilter: false,
        editBtn: false,
        enableVisibility: false,
        showAllForLegend: false,
        isTableView: false,
      },
      localMachines: [],
      isFiltered: false,
    },
    {
      template: "machinesLoadGraph",
      name: "MACHINES_LOAD_GRAPH",
      clone: false,
      ID: "6",
      options: {
        display: true,
        duplicate: true,
        disableExport: true,
        width: 6,
        disablePie: true,
        selectedGraph: "bar",
        disableTable: true,
        disableClose: false,
        rotateBar: false,
        header: "Machines Load",
        disableBar: true,
        settings: { 
          parameter: "", scale: 1, planClicked: false, parameters: [],colorMode:true,targetMode:false,gradedMode:true,customization: 'values',percentageChoice : "target" 
        },
        line: 3,
        defaultGraph: "pie",
        height: 500,
        maxHeight: 500,
        tableSelected: false,
        printDiv: "shiftContainerGraphPrint",
        rotateH: false,
        legend: false,
        hideSettings: false,
        sizable: true,
        displayFilter: false,
        editBtn: false,
        enableVisibility: false,
        showAllForLegend: false,
        compareBtn: false,
        tableButton: false,
        isTableView: false,
      },
      localMachines: [],
      isFiltered: false,
      change: 0,
    },
    {
      template: "unitsProducedTheoretically",
      name: "UNITS_PRODUCED_THEORETICALLY",
      clone: false,
      ID: "17",
      options: {
        display: true,
        duplicate: true,
        disableExport: true,
        width: 6,
        disablePie: true,
        selectedGraph: "bar",
        disableTable: true,
        disableClose: false,
        rotateBar: false,
        header: "Machines Load",
        disableBar: true,
        settings: { 
          parameter: "", scale: 1, planClicked: false, parameters:  [],colorMode:true,targetMode:false,gradedMode:true,customization: 'values',percentageChoice : "target" 
        },
        line: 3,
        defaultGraph: "pie",
        height: 500,
        maxHeight: 500,
        tableSelected: false,
        printDiv: "shiftContainerGraphPrint",
        rotateH: false,
        legend: false,
        hideSettings: false,
        sizable: true,
        displayFilter: false,
        editBtn: false,
        enableVisibility: false,
        showAllForLegend: false,
        compareBtn: false,
        tableButton: false,
        isTableView: false,
      },
      localMachines: [],
      isFiltered: false,
      change: 0,
    },
    {
      template: "machinesLoadBarGraph",
      name: "Machines Load Bar",
      clone: false,
      ID: "7",
      options: {
        display: true,
        duplicate: true,
        disableExport: true,
        width: 6,
        disablePie: true,
        selectedGraph: "bar",
        disableTable: true,
        disableClose: false,
        rotateBar: false,
        header: "Machines Load Bar",
        disableBar: true,
        settings: { parameter: "", scale: 1, planClicked: false, parameters: [],colorMode:true,targetMode:false,gradedMode:true,percentageChoice:'target' },
        line: 3,
        defaultGraph: "pie",
        height: 500,
        maxHeight: 500,
        tableSelected: false,
        printDiv: "shiftContainerGraphPrint",
        rotateH: false,
        legend: false,
        hideSettings: false,
        sizable: true,
        displayFilter: false,
        editBtn: false,
        enableVisibility: false,
        showAllForLegend: false,
        compareBtn: false,
        tableButton: false,
        isTableView: false,
      },
      localMachines: [],
      isFiltered: false,
      change: 0,
    },
    {
      template: "shiftInsightGraph",
      name: "shift insights",
      clone: false,
      ID: "8",
      options: {
        machine: true,
        display: false,
        duplicate: true,
        width: 6,
        disablePie: true,
        selectedGraph: "bar",
        disableTable: true,
        disableClose: false,
        rotateBar: false,
        header: "",
        disableBar: true,
        tableButton: false,
        settings: {
          parameter: 2,
          parameters: [
            { index: 0, value: "Unexpected stop events to reported and unreported- by machine", api: "GetReportedMachineEventsByStartTime" },
            { index: 1, value: "Unexpected stop events to reported and unreported- Pie chart", api: "GetTotalReportedEventsByTypeByStartTime" },
            { index: 2, value: "OEE1 losses - by machine", api: "GetMachineLostOEETimeByStartTime" },
            { index: 3, value: "Time distribution - by machine", api: "GetMachineAvailabilityOEELostTimeByStartTime" },
            { index: 4, value: "Rejects reasons - by machine", api: "GetMachineRejectsDistributionByStartTime" },
            { index: 5, value: "KPIs", api: "GetDepartmentKPIsByTime" },
          ],
          scale: 1,
          planClicked: false,
        },
        line: 2,
        defaultGraph: "pie",
        disableExport: false,
        height: 500,
        maxHeight: 500,
        tableSelected: false,
        printDiv: "shiftContainerGraphPrint",
        rotateH: false,
        legend: false,
        hideSettings: false,
        sizable: true,
        displayFilter: false,
        editBtn: false,
        enableVisibility: false,
        showAllForLegend: false,
        compareBtn: false,
        isTableView: false,
      },
      localMachines: [],
      isFiltered: false,
    },  
    {
      template: "shiftInsightGraphWithoutParams",
      name: "KPIs by machines",
      templateV2:"KPIsByMachines",//to add 
      clone: false,
      ID: "13",
      options: {
        machine: true,
        display: false,
        duplicate: true,
        width: 6,
        disablePie: true,
        selectedGraph: "bar",
        disableTable: true,
        disableClose: false,
        rotateBar: false,
        header: "KPIS_BY_MACHINES",
        disableBar: true,
        tableButton: false,
        settings: {
          parameter: 0,
          parameters: [
            { index: 0, value: "", api: "GetMachinesKPIMeasuresByStartTime"}
          ],
          scale: 1,
          planClicked: false,
          colorMode:true,targetMode:false,percentageChoice : "target"
        },
        line: 2,
        defaultGraph: "pie",
        disableExport: true,
        height: 500,
        maxHeight: 500,
        tableSelected: false,
        printDiv: "shiftContainerGraphPrint",
        rotateH: false,
        legend: false,
        hideSettings: false,
        sizable: true,
        displayFilter: false,
        editBtn: false,
        enableVisibility: false,
        showAllForLegend: false,
        compareBtn: false,
        isTableView: false,
      },
      localMachines: [],
      isFiltered: false,
    },
    {
      template: "shiftInsightGraphWithoutParams",
      name: "KPIs by Shifts",
      templateV2:"KPIsByShifts",//to add 
      clone: false,
      ID: "14",
      options: {
        machine: true,
        display: false,
        duplicate: true,
        width: 6,
        disablePie: true,
        selectedGraph: "bar",
        disableTable: true,
        disableClose: false,
        rotateBar: false,
        header: "KPIS_BY_SHIFTS",
        disableBar: true,
        tableButton: false,
        settings: {
          parameter: 0,
          parameters: [
            { index: 0, value: "", api: "GetShiftsKPIMeasuresByStartTime"}
          ],
          scale: 1,
          planClicked: false,
          colorMode:true,targetMode:false,percentageChoice : "target"
        },
        line: 2,
        defaultGraph: "pie",
        disableExport: true,
        height: 500,
        maxHeight: 500,
        tableSelected: false,
        printDiv: "shiftContainerGraphPrint",
        rotateH: false,
        legend: false,
        hideSettings: false,
        sizable: true,
        displayFilter: false,
        editBtn: false,
        enableVisibility: false,
        showAllForLegend: false,
        compareBtn: false,
        isTableView: false,
      },
      localMachines: [],
      isFiltered: false,
    },
    {
      template: "unitsProducedGraph",
      name: "Units Produced",
      clone: false,
      ID: "9",
      options: {
        display: false,
        duplicate: true,
        width: 6,
        disablePie: true,
        selectedGraph: "bar",
        disableTable: true,
        disableClose: false,
        rotateBar: false,
        header: "Units Produced",
        isableTable: true,
        tableButton: true,
        compareBtn: true,
        disableBar: true,
        printDiv: "shiftContainerGraphPrint",
        settings: { compareWith: "none", compare: false, compareLabel: "NIL", parameter: 0, scale: 1, planClicked: false },
        line: 3,
        defaultGraph: "pie",
        disableExport: false,
        height: 500,
        maxHeight: 500,
        tableSelected: false,
        rotateH: false,
        legend: false,
        hideSettings: false,
        sizable: true,
        displayFilter: false,
        editBtn: false,
        enableVisibility: false,
        showAllForLegend: false,
        isTableView: false,
      },
      localMachines: [],
      isFiltered: false,
    },
    {
      template: "topRejectsGraph",
      name: "Top Rejects",
      clone: false,
      ID: "10",
      options: {
        display: false,
        duplicate: true,
        width: 6,
        disablePie: true,
        selectedGraph: "bar",
        disableTable: true,
        disableClose: false,
        rotateBar: false,
        header: "Top 5 Rejects",
        disableBar: true,
        tableButton: true,
        settings: { top: 5, parameter: 0, parameters: [], division: true, showScale: true, isScaled: false, scale: 1, planClicked: false },
        line: 3,
        defaultGraph: "pie",
        disableExport: false,
        height: 500,
        maxHeight: 500,
        tableSelected: false,
        printDiv: "shiftContainerGraphPrint",
        rotateH: false,
        legend: false,
        hideSettings: false,
        sizable: true,
        displayFilter: false,
        editBtn: false,
        enableVisibility: false,
        showAllForLegend: false,
        compareBtn: false,
        isTableView: false,
      },
      localMachines: [],
      isFiltered: false,
    },
    {
      template: "shiftInsightGraph",
      name: "shift insights",
      clone: true,
      ID: "11",
      options: {
        machine: true,
        display: false,
        duplicate: true,
        width: 6,
        disablePie: true,
        selectedGraph: "bar",
        disableTable: true,
        disableClose: false,
        rotateBar: false,
        header: "",
        disableBar: true,
        tableButton: false,
        settings: {
          parameter: 1,
          parameters: [
            { index: 0, value: "Unexpected stop events to reported and unreported- by machine", api: "GetReportedMachineEventsByStartTime" },
            { index: 1, value: "Unexpected stop events to reported and unreported- Pie chart", api: "GetTotalReportedEventsByTypeByStartTime" },
            { index: 2, value: "OEE1 losses - by machine", api: "GetMachineLostOEETimeByStartTime" },
            { index: 3, value: "Time distribution - by machine", api: "GetMachineAvailabilityOEELostTimeByStartTime" },
            { index: 4, value: "Rejects reasons - by machine", api: "GetMachineRejectsDistributionByStartTime" },
            { index: 5, value: "KPIs", api: "GetDepartmentKPIsByTime" },
          ],
          scale: 1,
          planClicked: false,
        },
        line: 4,
        defaultGraph: "pie",
        disableExport: false,
        height: 500,
        maxHeight: 500,
        tableSelected: false,
        printDiv: "shiftContainerGraphPrint",
        rotateH: false,
        legend: false,
        hideSettings: false,
        sizable: true,
        displayFilter: false,
        editBtn: false,
        enableVisibility: false,
        showAllForLegend: false,
        compareBtn: false,
        isTableView: false,
      },
      localMachines: [],
      isFiltered: false,
    },
    {
      template: "machinePlanGraph",
      name: "plansGraph",
      clone: false,
      ID: "3",
      options: {
        display: true,
        duplicate: true,
        enableVisibility: true,
        width: 6,
        disablePie: true,
        selectedGraph: "bar",
        disableTable: true,
        disableClose: false,
        rotateBar: false,
        header: "Machine Availablitiy:Planned Schedule vs. Actual",
        disableBar: true,
        settings: { scale: 1, planClicked: true, filterM: { selectAll: true } },
        line: 4,
        defaultGraph: "pie",
        disableExport: false,
        height: 500,
        maxHeight: 500,
        tableSelected: false,
        printDiv: "shiftContainerGraphPrint",
        rotateH: false,
        legend: false,
        hideSettings: false,
        sizable: true,
        displayFilter: false,
        editBtn: false,
        showAllForLegend: false,
        compareBtn: false,
        tableButton: false,
        isTableView: false,
      },
      localMachines: [],
      isFiltered: false,
      change: 0,
    },
    {
      template: "topStopEventsGraph",
      name: "Top stop events",
      clone: false,
      ID: "12",
      options: {
        display: true,
        duplicate: true,
        width: 6,
        disablePie: true,
        selectedGraph: "table",
        disableTable: true,
        disableClose: false,
        rotateBar: false,
        header: "Top 5 Stop Events",
        disableBar: true,
        tableButton: true,
        settings: {
          top: 5,
          parameter: 0,
          parameters: [
            { index: 0, value: "TOP_STOP_EVENT_REASONS" },
            { index: 1, value: "TOP_STOP_EVENT_GROUPS" },
          ],
          division: false,
          groupByEvent: true,
          timeV: true,
          scale: 1,
          planClicked: false,
          filterR: { 0: true, 18: true, 100: true, 310: true, 325: true, selectAll: true },
          filterG: { 1: true, 6: true, 10: true, 12: true, selectAll: true },
        },
        line: 4,
        defaultGraph: "pie",
        disableExport: false,
        height: 500,
        maxHeight: 500,
        tableSelected: false,
        printDiv: "shiftContainerGraphPrint",
        rotateH: false,
        legend: false,
        hideSettings: false,
        sizable: true,
        displayFilter: false,
        editBtn: false,
        enableVisibility: false,
        showAllForLegend: false,
        compareBtn: false,
        isTableView: false,
      },
      localMachines: [],
      isFiltered: false,
      change: 0,
    },
  ];

  return {
    shiftData: shiftData,
    gridDefault: gridDefault,
    machineContainersDefault: machineContainersDefault,
    containersDefault: containersDefault,
  };
});
